services:
  app:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - ./:/app:delegated
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: >
      sh -c "
        bun install
        bun run db:migrate
        bun run db:generate
        bun run dev
      "

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parkirdw_db
    ports:
      - "5432:5432"
    volumes:
      - database_volume:/var/lib/postgresql/data

volumes:
  database_volume:
